### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by sabman** [jensleitloff/CNN-Sentinel#2]
Hi all thanks for the great tutorial! 
Quick question: is it possible to get a hold of the pretrained model for MS Imagery mentioned here https://github.com/jensleitloff/CNN-Sentinel/blob/master/py/06_classify_image.py#L18 I can't seem to be able to find it anywhere.
Many thanks!

**Comment by jensleitloff** [comment]
For a limited time, I put the trained models in my Google drive:
https://drive.google.com/drive/folders/1QgNqfRQ7aZraO83Jv3bVCWDC9lLmZV2r?usp=sharing
Your requested model is in the vgg_net folder.

If I run out of space on Google drive, I have to delete those models.
