### ISSUE TITLE
Interpretation of 06_classify_image.py outputs

### ISSUE THREAD

**Issue by tonyboston-au** [jensleitloff/CNN-Sentinel#4]
@jensleitloff - thanks very much for your tutorial and code which is very useful.
06_classify_image.py by default produces two outputs: a label.tif file and a prob.tif file. The label TIF file when I run the code on a VGG RGB model built using transfer learning is a grayscale image with 10 'colours' that presumably correspond to the 10 land cover classes in the eurosat dataset? Is there a legend you could share that relates the results in this TIF image to those classes?
The prob.tif output file may be the probability by pixel of the selected class? Any more information about this output is appreciated.
Thanks

**Comment by jensleitloff** [comment]
Yes, the 10 colours are the classes. You can determine the corresponding classes by yourself from [02_train_rgb_finetuning.py](https://github.com/jensleitloff/CNN-Sentinel/blob/master/py/02_train_rgb_finetuning.py). Line [78](https://github.com/jensleitloff/CNN-Sentinel/blob/9bf67d50783873bbb034b0eb6ee6255a3a5a1c0b/py/02_train_rgb_finetuning.py#L78) to 80 prints your training classes:
```
# just for information
class_indices = train_generator.class_indices
print(class_indices)
```
And a further yes to the the prob.tif. This is the probability of the class in label.tif. During classification the probability of all classes are predicted for each pixel. Then, the class with the highest probability is selected. You can see this in line [76](https://github.com/jensleitloff/CNN-Sentinel/blob/9bf67d50783873bbb034b0eb6ee6255a3a5a1c0b/py/06_classify_image.py#L76)

**Comment by tonyboston-au** [comment]
Thanks very much Jens

**Comment by tonyboston-au** [comment]
@jensleitloff I'm having trouble interpreting the classes created by a model in the label.tif file. 02_train_rgb_finetuning.py outputs the classes as: 
Found 18900 images belonging to 10 classes.
{'AnnualCrop': 0, 'Forest': 1, 'HerbaceousVegetation': 2, 'Highway': 3, 'Industrial': 4, 'Pasture': 5, 'PermanentCrop': 6, 'Residential': 7, 'River': 8, 'SeaLake': 9}
Found 8100 images belonging to 10 classes.
...
When I review the grayscale TIF image created by 06_classify_image.py, the classes don't make sense. For example, the forest class (identified by overlaying the Sentinel-2 satellite image) is displayed as class #9 #090909, which according to the above legend should be the class 'SeaLake'. Any advice is really appreciated.
