### ISSUE TITLE
There is a paper?

### ISSUE THREAD

**Issue by toniesteves** [jensleitloff/CNN-Sentinel#5]
Hi, first of all, congratulations on your work. I wanna know if there is some paper about your work?

**Comment by felixriese** [comment]
Hi @toniesteves,

Thanks! We are working on a publication for 2020. For other publications, you can refer to
- [Jens Leitloff @ Google Scholar](https://scholar.google.de/citations?user=9LB9sF4AAAAJ&hl=de&oi=ao)
- [Felix Riese @ Google Scholar](https://scholar.google.de/citations?user=eO2gSwUAAAAJ&hl=de)

and cite the code via

> Jens Leitloff and Felix M. Riese, "Examples for CNN training and classification on Sentinel-2 data", Zenodo, [10.5281/zenodo.3268451](http://doi.org/10.5281/zenodo.3268451), 2018.

and bibtex:

```tex
@misc{leitloff2018examples,
    author = {Leitloff, Jens and Riese, Felix~M.},
    title = {{Examples for CNN training and classification on Sentinel-2 data}},
    year = {2018},
    DOI = {10.5281/zenodo.3268451},
    publisher = {Zenodo},
    howpublished = {\href{http://doi.org/10.5281/zenodo.3268451}{http://doi.org/10.5281/zenodo.3268451}}
}
```

Best, Felix
