### ISSUE TITLE
Interpretation of 06_classify_image.py outputs (again)

### ISSUE THREAD

**Issue by tonyboston-au** [jensleitloff/CNN-Sentinel#6]
@jensleitloff I'm having trouble interpreting the classes created by a model in the label.tif file. 02_train_rgb_finetuning.py outputs the classes as:
Found 18900 images belonging to 10 classes.
{'AnnualCrop': 0, 'Forest': 1, 'HerbaceousVegetation': 2, 'Highway': 3, 'Industrial': 4, 'Pasture': 5, 'PermanentCrop': 6, 'Residential': 7, 'River': 8, 'SeaLake': 9}
Found 8100 images belonging to 10 classes.
...
When I review the grayscale TIF image created by 06_classify_image.py, the classes don't make sense. For example, the forest class (identified by overlaying the Sentinel-2 satellite image) is displayed as class #9 #090909, which according to the above legend should be the class 'SeaLake'. I must be doing something wrong! 

Any advice is really appreciated.

**Comment by jensleitloff** [comment]
Unfortunately, it's hard to give any useful advice based on your comment. In our tests the classification was fine (even so, not good as segmentation approaches). What do you mean by 
> #090909 

Normally you should have one label per pixel. Have you tested our  [pretrained models]( https://github.com/jensleitloff/CNN-Sentinel/issues/2#issuecomment-504924194)? Maybe something went wrong during training.

**Comment by jensleitloff** [comment]
Please also check, that the data you intend to classify, has the same preprocessing as the EuroSAT dataset. We already had this problem in a previous [issue](https://github.com/jensleitloff/CNN-Sentinel/issues/3)

**Comment by tonyboston-au** [comment]
Thanks @jensleitloff for those suggestions. Yes I downloaded your models a few months ago so can try those and will check that the Sentinel data is prepared the same way as described in that issue.

**Comment by felixriese** [comment]
Are you on the latest version of the repository, @tonyboston-au ? Please do a  
```
git pull
```
since in e956484cdb73be2b5f62efd83aaa2557216e5c34 we fixed a bug.

**Comment by tonyboston-au** [comment]
okay will do - thanks @felixriese
