### ISSUE TITLE
Value range 0.67-0.83 of ms_prob - why not get an integer value

### ISSUE THREAD

**Issue by felixriese** [jensleitloff/CNN-Sentinel#8]
@felixriese 
I know you mean.
Thanks very much for the assistance you provide my help.

More further,I obtain result of S2 image. But I don't know value range 0.67-0.83 of ms_prob why not get an integer value. [attachment figure](https://drive.google.com/file/d/1qdg4pz7BbdjdGPhtFXLGtJi6QHm5xILn/view?usp=sharing)

Sorry to bother you.

_Originally posted by @daniellinboy in https://github.com/jensleitloff/CNN-Sentinel/issues/7#issuecomment-546968534_

**Comment by felixriese** [comment]
@daniellinboy I have moved your question to a new issue since it is. completely different.

There are two files:
* `ms_prob` contains the confidence (continuous, float between 0 and 1) of the classifier for the respective label
* `ms_label` contains the label (discrete) which the classifier assigned

If you want to know the result of the classifier, use `ms_label`.

Does that answer your question?

**Comment by daniellinboy** [comment]
Thank you very much and I have knows output file! 

But I have met other problems, ms_label only 0 and 10, not have 1 - 9 kinds. 
Currently testing images in mountainous areas. (use Sentinel-2 RGB bands image)

What should I consider when test images?

**Comment by felixriese** [comment]
@daniellinboy Please create a new issue for every independent question.
