### ISSUE TITLE
ms_label only 0 and 10, not have 1 - 9

### ISSUE THREAD

**Issue by felixriese** [jensleitloff/CNN-Sentinel#9]
But I have met other problems, ms_label only 0 and 10, not have 1 - 9 kinds. 
Currently testing images in mountainous areas. (use Sentinel-2 RGB bands image)

What should I consider when test images?

_Originally posted by @daniellinboy in https://github.com/jensleitloff/CNN-Sentinel/issues/8#issuecomment-547487455_

**Comment by felixriese** [comment]
@daniellinboy What data are you using? Does the test data have the same classes as the training data? Are you sure, that the order of the Sentinel-2 bands is correct?

Please have a look at previous issues #3 , #4 , #5.

**Comment by jensleitloff** [comment]
As you are using RGB images, check correct scaling. We already addressed this in issue #1.

**Comment by daniellinboy** [comment]
Thank you again for your valuable suggestions.
@felixriese 
I trained the data using EuroSAT data and then tested the area almost in the mountains.
Thank you for your reminder, I forgot to sure the test area with similar training data. [attachment_test area](https://drive.google.com/file/d/1PDKB0JYz-r9DLWUWn8ATfSPGDufqkwyg/view?usp=sharing)

@jensleitloff 
I am not using the code, I also guess that there will be a scale problem, thank you for providing such a good solve direction.

**Comment by felixriese** [comment]
@daniellinboy I am not sure how to use your example image. Is the issue resolved?
